Feature/regtest address
ActorForth/slpdb pull request #1
Opened 2020-11-10 07:45 UTC by SuperCipher

merge to release commit

2020-11-10 07:58 UTC, litvinof requested changes
One comment left, other than that - LGTM

2020-11-10 07:58 UTC, litvinof commented on index.ts
> +
Wouldn't it look cleaner if we change this to look something like

```
const chainsAvailable = [′mainnet′, ′testnet′, ‘regtest‘]
let network = networksAvailable.includes(chain) ? chain : ′mainnet'
```

2020-11-10 08:01 UTC, nicolaiskye commented on slptokengraph.ts
> +            } else{
Maybe I'm nitpicking, but I think
`} else {`
with an extra space looks more clean.

2020-11-10 08:03 UTC, nicolaiskye commented on tna.ts
> +        let net : string
Same thing here as @litvinof mentioned on the index.ts file.

2020-11-10 08:03 UTC, nicolaiskye commented on tna.ts
> +                      } else{
More nitpicking
`} else {`

2020-11-10 09:22 UTC, nicolaiskye approved these changes
LGTM

2020-11-11 04:45 UTC, litvinof approved these changes

2020-11-11 04:45 UTC, merged